### ISSUE TITLE
How to turn disable flags that default to true?

### ISSUE THREAD

**Issue by noahsw** [symblai/speech-recognition-evaluation#2]
https://github.com/symblai/speech-recognition-evaluation/blob/637645a6156c4e6f926d4a1ef53c4cdc69f693cc/index.js#L125

I've tried:
`--lowercase=false`
`--lowercase false`
`--no-lowercase`
`--lowercase:false`

Reference: https://github.com/75lb/command-line-args/issues/108

**Comment by toshish** [comment]
@noahsw New version supports it now - https://github.com/symblai/speech-recognition-evaluation/releases/tag/v1.1.0

This should work now - 
`--lowercase false`
